// <auto-generated />
using System;
using FaceAlbum.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace FaceAlbum.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20190717093310_DDL_DB_FACE_ALBUM")]
    partial class DDL_DB_FACE_ALBUM
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("FaceAlbum.Models.Album", b =>
                {
                    b.Property<int>("AlbumId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Fim");

                    b.Property<string>("FotoTopo")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("Inicio");

                    b.HasKey("AlbumId");

                    b.ToTable("Albuns");
                });

            modelBuilder.Entity("FaceAlbum.Models.Imagem", b =>
                {
                    b.Property<int>("ImagemId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AlbumId");

                    b.Property<string>("Link")
                        .IsRequired();

                    b.HasKey("ImagemId");

                    b.HasIndex("AlbumId");

                    b.ToTable("Imagens");
                });

            modelBuilder.Entity("FaceAlbum.Models.Imagem", b =>
                {
                    b.HasOne("FaceAlbum.Models.Album", "Album")
                        .WithMany("Imagens")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
